---
env:
  browser: true
  node: true
  jasmine: true
parser: babel-eslint
extends: airbnb
plugins: ["react"]
rules:
  jsx-a11y/href-no-hash: off
  jsx-a11y/anchor-is-valid: ["warn",{"aspects":["invalidHref"]}]
  jsx-a11y/no-static-element-interactions: ["error",{ "handlers": ['onClick','onMouseDown','onMouseUp','onKeyPress','onKeyDown','onKeyUp',],},]
  react/forbid-prop-types: ['error',{forbid:[]}]
  react/no-multi-comp: [ 'error', { 'ignoreStateless': true }]
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  import/extensions: ['error', 'always', { js: 'never', jsx: 'never'}]
