const ADD_TODO = 'ADD_TODO';
const REMOVE_TODO = 'REMOVE_TODO';
const COUNT_INCREMENT = 'INCREMENT';
const COUNT_DECREMENT = 'DECREMENT';
const WINDOW_RESIZE_HEIGHT = 'WINDOW_RESIZE_HEIGHT';
const WINDOW_RESIZE_WIDTH = 'WINDOW_RESIZE_WIDTH';

export default {
  WINDOW_RESIZE_HEIGHT,
  WINDOW_RESIZE_WIDTH,
  ADD_TODO,
  REMOVE_TODO,
  COUNT_INCREMENT,
  COUNT_DECREMENT,
};
