const ADD_TODO = 'ADD_TODO';
const REMOVE_TODO = 'REMOVE_TODO';
const COUNT_INCREMENT = 'INCREMENT';
const COUNT_DECREMENT = 'DECREMENT';
const WINDOW_RESIZE_WIDTH = 'WINDOW_RESIZE_WIDTH';
const LAYOUT_RESIZE_HEIGHT = 'LAYOUT_RESIZE_HEIGHT';
const LAYOUT_TOGGLE_SIDE_MENU = 'LAYOUT_TOGGLE_SIDE_MENU';

// TASKJOB
const PAGE_TASKJOB = 'PAGE_TASKJOB';
const OPEN_TASKJOB = 'OPEN_TASKJOB';
const GET_TASKJOB = 'GET_TASKJOB';
const CANCEL_TASKJOB = 'CANCEL_TASKJOB';
const RESET_TASKJOB = 'RESET_TASKJOB';
const OPEN_SEARCH_COL_TASKJOB = 'OPEN_SEARCH_COL_TASKJOB';
const CHANGE_SEARCH_COL_TASKJOB = 'CHANGE_SEARCH_COL_TASKJOB';
const SELECT_TASK_JOB_INTERVAL_TYPE = 'SELECT_TASK_JOB_INTERVAL_TYPE';


const PAGE_TASKJOBLOG = 'PAGE_TASKJOBLOG';
const OPEN_TASKJOBLOG = 'OPEN_TASKJOBLOG';
const GET_TASKJOBLOG = 'GET_TASKJOBLOG';
const CANCEL_TASKJOBLOG = 'CANCEL_TASKJOBLOG';
const RESET_TASKJOBLOG = 'RESET_TASKJOBLOG';
const OPEN_SEARCH_COL_TASKJOBLOG = 'OPEN_SEARCH_COL_TASKJOBLOG';
const CHANGE_SEARCH_COL_TASKJOBLOG = 'CHANGE_SEARCH_COL_TASKJOBLOG';
const LATESTLOG_TASKJOBLOG = 'LATESTLOG_TASKJOBLOG'

// ERROR
const CATCH_ERROR = 'CATCH_ERROR';


export default {
  LAYOUT_TOGGLE_SIDE_MENU,
  LAYOUT_RESIZE_HEIGHT,
  WINDOW_RESIZE_WIDTH,
  ADD_TODO,
  REMOVE_TODO,
  COUNT_INCREMENT,
  COUNT_DECREMENT,

  PAGE_TASKJOB,
  OPEN_TASKJOB,
  GET_TASKJOB,
  CANCEL_TASKJOB,
  RESET_TASKJOB,
  OPEN_SEARCH_COL_TASKJOB,
  CHANGE_SEARCH_COL_TASKJOB,
  SELECT_TASK_JOB_INTERVAL_TYPE,

  PAGE_TASKJOBLOG,
  OPEN_TASKJOBLOG,
  GET_TASKJOBLOG,
  CANCEL_TASKJOBLOG,
  RESET_TASKJOBLOG,
  OPEN_SEARCH_COL_TASKJOBLOG,
  CHANGE_SEARCH_COL_TASKJOBLOG,
  LATESTLOG_TASKJOBLOG,


  CATCH_ERROR,
};
