const ADD_TODO = 'ADD_TODO';
const REMOVE_TODO = 'REMOVE_TODO';
const COUNT_INCREMENT = 'INCREMENT';
const COUNT_DECREMENT = 'DECREMENT';
const WINDOW_RESIZE_WIDTH = 'WINDOW_RESIZE_WIDTH';
const LAYOUT_RESIZE_HEIGHT = 'LAYOUT_RESIZE_HEIGHT';
const LAYOUT_TOGGLE_SIDE_MENU = 'LAYOUT_TOGGLE_SIDE_MENU';

// TASKJOB
const PAGE_TASKJOB = 'PAGE_TASKJOB';
const OPEN_TASKJOB = 'OPEN_TASKJOB';
const GET_TASKJOB = 'GET_TASKJOB';
const CANCEL_TASKJOB = 'CANCEL_TASKJOB';
const RESET_TASKJOB = 'RESET_TASKJOB';
const OPEN_SEARCH_COL_TASKJOB = 'OPEN_SEARCH_COL_TASKJOB';
const CHANGE_SEARCH_COL_TASKJOB = 'CHANGE_SEARCH_COL_TASKJOB';
// ERROR
const CATCH_ERROR = 'CATCH_ERROR';


export default {
  LAYOUT_TOGGLE_SIDE_MENU,
  LAYOUT_RESIZE_HEIGHT,
  WINDOW_RESIZE_WIDTH,
  ADD_TODO,
  REMOVE_TODO,
  COUNT_INCREMENT,
  COUNT_DECREMENT,
  PAGE_TASKJOB,
  OPEN_TASKJOB,
  GET_TASKJOB,
  CANCEL_TASKJOB,
  RESET_TASKJOB,
  OPEN_SEARCH_COL_TASKJOB,
  CHANGE_SEARCH_COL_TASKJOB,
  CATCH_ERROR,
};
